apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-o2xz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: componenta-devfile-sample-go-basic-private-devfile-nested-o2xz
    app.kubernetes.io/part-of: mc-golang-nested
  name: componenta-devfile-sample-go-basic-private-devfile-nested-o2xz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-o2xz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: componenta-devfile-sample-go-basic-private-devfile-nested-o2xz
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wnyj-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-o2xz@sha256:ab785d0f1b932701d01712b810b68c67946e07e266c078c2a7219f33edc9dd68
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 12m
            memory: 18Mi
status: {}
