apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: componenta-devfile-sample-go-basic-private-devfile-nested-o2xz
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wnyj-tenant/mc-golang-nested/componenta-devfile-sample-go-basic-private-devfile-nested-o2xz@sha256:ab785d0f1b932701d01712b810b68c67946e07e266c078c2a7219f33edc9dd68
        name: my-go
        resources: {}
status: {}
